list(list(package = "fBasics", family = "gh", family_info = list(
    lower = c(alpha = 0.01, beta = -0.99, delta = 0.01, mu = -Inf
    ), upper = c(alpha = Inf, beta = 0.99, delta = Inf, mu = Inf
    ), accepts_float = c(alpha = TRUE, beta = TRUE, delta = TRUE, 
    mu = TRUE), defaults = c(alpha = 1, beta = 0, delta = 1, 
    mu = 0), log = TRUE, discrete = FALSE, support_min = -Inf, 
    support_max = Inf, supp_max_depends_on = c(alpha = FALSE, 
    beta = FALSE, delta = FALSE, mu = FALSE), supp_min_depends_on = c(alpha = FALSE, 
    beta = FALSE, delta = FALSE, mu = FALSE))), list(package = "fBasics", 
    family = "ght", family_info = list(lower = c(beta = -Inf, 
    delta = 0.01, mu = -Inf, nu = -303.18), upper = c(beta = Inf, 
    delta = Inf, mu = Inf, nu = 301.18), accepts_float = c(beta = TRUE, 
    delta = TRUE, mu = TRUE, nu = TRUE), defaults = c(beta = 0.1, 
    delta = 1, mu = 0, nu = 10), log = TRUE, discrete = FALSE, 
        support_min = -Inf, support_max = Inf, supp_max_depends_on = c(beta = FALSE, 
        delta = FALSE, mu = FALSE, nu = FALSE), supp_min_depends_on = c(beta = FALSE, 
        delta = FALSE, mu = FALSE, nu = FALSE))), list(package = "fBasics", 
    family = "hyp", family_info = list(lower = c(alpha = 0.01, 
    beta = -0.99, delta = 0.01, mu = -Inf), upper = c(alpha = 709.78, 
    beta = 0.99, delta = 709.78, mu = Inf), accepts_float = c(alpha = TRUE, 
    beta = TRUE, delta = TRUE, mu = TRUE), defaults = c(alpha = 1, 
    beta = 0, delta = 1, mu = 0), log = TRUE, discrete = FALSE, 
        support_min = -Inf, support_max = Inf, supp_max_depends_on = c(alpha = FALSE, 
        beta = FALSE, delta = FALSE, mu = FALSE), supp_min_depends_on = c(alpha = FALSE, 
        beta = FALSE, delta = FALSE, mu = FALSE))), list(package = "fBasics", 
    family = "nig", family_info = list(lower = c(alpha = 0.01, 
    beta = -0.99, delta = 0.01, mu = -Inf), upper = c(alpha = Inf, 
    beta = 0.99, delta = Inf, mu = Inf), accepts_float = c(alpha = TRUE, 
    beta = TRUE, delta = TRUE, mu = TRUE), defaults = c(alpha = 1, 
    beta = 0, delta = 1, mu = 0), log = TRUE, discrete = FALSE, 
        support_min = -Inf, support_max = Inf, supp_max_depends_on = c(alpha = FALSE, 
        beta = FALSE, delta = FALSE, mu = FALSE), supp_min_depends_on = c(alpha = FALSE, 
        beta = FALSE, delta = FALSE, mu = FALSE))), list(package = "fBasics", 
    family = "sgh", family_info = list(lower = c(zeta = 0.01, 
    rho = -0.99, lambda = -150.96), upper = c(zeta = Inf, rho = 0.99, 
    lambda = 148.96), accepts_float = c(zeta = TRUE, rho = TRUE, 
    lambda = TRUE), defaults = c(zeta = 1, rho = 0, lambda = 1
    ), log = TRUE, discrete = FALSE, support_min = -Inf, support_max = Inf, 
        supp_max_depends_on = c(zeta = FALSE, rho = FALSE, lambda = FALSE
        ), supp_min_depends_on = c(zeta = FALSE, rho = FALSE, 
        lambda = FALSE))), list(package = "fBasics", family = "sght", 
    family_info = list(lower = c(beta = -Inf, delta = 0.01, mu = -Inf, 
    nu = -303.18), upper = c(beta = Inf, delta = Inf, mu = Inf, 
    nu = 301.18), accepts_float = c(beta = TRUE, delta = TRUE, 
    mu = TRUE, nu = TRUE), defaults = c(beta = 0.1, delta = 1, 
    mu = 0, nu = 10), log = TRUE, discrete = FALSE, support_min = -Inf, 
        support_max = Inf, supp_max_depends_on = c(beta = FALSE, 
        delta = FALSE, mu = FALSE, nu = FALSE), supp_min_depends_on = c(beta = FALSE, 
        delta = FALSE, mu = FALSE, nu = FALSE))), list(package = "fBasics", 
    family = "snig", family_info = list(lower = c(zeta = 0.01, 
    rho = -0.99), upper = c(zeta = Inf, rho = 0.99), accepts_float = c(zeta = TRUE, 
    rho = TRUE), defaults = c(zeta = 1, rho = 0), log = TRUE, 
        discrete = FALSE, support_min = -Inf, support_max = Inf, 
        supp_max_depends_on = c(zeta = FALSE, rho = FALSE), supp_min_depends_on = c(zeta = FALSE, 
        rho = FALSE))))
