list(list(package = "GeneralizedHyperbolic", family = "ghyp", 
    family_info = list(lower = c(mu = -Inf, delta = 0.01, alpha = 0.01, 
    beta = -0.99, lambda = -245.82), upper = c(mu = Inf, delta = Inf, 
    alpha = Inf, beta = 0.99, lambda = 246.82), accepts_float = c(mu = TRUE, 
    delta = TRUE, alpha = TRUE, beta = TRUE, lambda = TRUE), 
        defaults = c(mu = 0, delta = 1, alpha = 1, beta = 0, 
        lambda = 1), log = FALSE, discrete = FALSE, support_min = -Inf, 
        support_max = Inf, supp_max_depends_on = c(mu = FALSE, 
        delta = FALSE, alpha = FALSE, beta = FALSE, lambda = FALSE
        ), supp_min_depends_on = c(mu = FALSE, delta = FALSE, 
        alpha = FALSE, beta = FALSE, lambda = FALSE))), list(
    package = "GeneralizedHyperbolic", family = "gig", family_info = list(
        lower = c(chi = 0.01, psi = 0.01, lambda = -Inf), upper = c(chi = Inf, 
        psi = Inf, lambda = Inf), accepts_float = c(chi = TRUE, 
        psi = TRUE, lambda = TRUE), defaults = c(chi = 1, psi = 1, 
        lambda = 1), log = FALSE, discrete = FALSE, support_min = 0.0100000000000051, 
        support_max = Inf, supp_max_depends_on = c(chi = FALSE, 
        psi = FALSE, lambda = FALSE), supp_min_depends_on = c(chi = FALSE, 
        psi = FALSE, lambda = FALSE))), list(package = "GeneralizedHyperbolic", 
    family = "hyperb", family_info = list(lower = c(mu = -Inf, 
    delta = 0.01, alpha = 0.01, beta = -0.99), upper = c(mu = Inf, 
    delta = Inf, alpha = Inf, beta = 0.99), accepts_float = c(mu = TRUE, 
    delta = TRUE, alpha = TRUE, beta = TRUE), defaults = c(mu = 0, 
    delta = 1, alpha = 1, beta = 0), log = FALSE, discrete = FALSE, 
        support_min = -Inf, support_max = Inf, supp_max_depends_on = c(mu = FALSE, 
        delta = FALSE, alpha = FALSE, beta = FALSE), supp_min_depends_on = c(mu = FALSE, 
        delta = FALSE, alpha = FALSE, beta = FALSE))), list(package = "GeneralizedHyperbolic", 
    family = "nig", family_info = list(lower = c(mu = -Inf, delta = 0.01, 
    alpha = 0.01, beta = -0.99), upper = c(mu = Inf, delta = Inf, 
    alpha = Inf, beta = 0.99), accepts_float = c(mu = TRUE, delta = TRUE, 
    alpha = TRUE, beta = TRUE), defaults = c(mu = 0, delta = 1, 
    alpha = 1, beta = 0), log = FALSE, discrete = FALSE, support_min = -Inf, 
        support_max = Inf, supp_max_depends_on = c(mu = FALSE, 
        delta = FALSE, alpha = FALSE, beta = FALSE), supp_min_depends_on = c(mu = FALSE, 
        delta = FALSE, alpha = FALSE, beta = FALSE))), list(package = "GeneralizedHyperbolic", 
    family = "skewlap", family_info = list(lower = c(mu = -Inf, 
    alpha = 0.01, beta = 0.01), upper = c(mu = Inf, alpha = Inf, 
    beta = Inf), accepts_float = c(mu = TRUE, alpha = TRUE, beta = TRUE
    ), defaults = c(mu = 0, alpha = 1, beta = 1), log = FALSE, 
        discrete = FALSE, support_min = -Inf, support_max = Inf, 
        supp_max_depends_on = c(mu = FALSE, alpha = FALSE, beta = FALSE
        ), supp_min_depends_on = c(mu = FALSE, alpha = FALSE, 
        beta = FALSE))))
