list(list(package = "TLMoments", family = "gev", family_info = list(
    lower = c(loc = -Inf, scale = 0.01, shape = -Inf), upper = c(loc = 719.78, 
    scale = Inf, shape = 950), accepts_float = c(loc = TRUE, 
    scale = TRUE, shape = TRUE), defaults = c(loc = 0, scale = 1, 
    shape = 0), log = FALSE, discrete = FALSE, support_min = -Inf, 
    support_max = Inf, supp_max_depends_on = c(loc = FALSE, scale = FALSE, 
    shape = FALSE), supp_min_depends_on = c(loc = FALSE, scale = FALSE, 
    shape = FALSE))), list(package = "TLMoments", family = "gpd", 
    family_info = list(lower = c(loc = -Inf, scale = 0.01, shape = -Inf
    ), upper = c(loc = Inf, scale = Inf, shape = Inf), accepts_float = c(loc = TRUE, 
    scale = TRUE, shape = TRUE), defaults = c(loc = 0, scale = 1, 
    shape = 0), log = FALSE, discrete = FALSE, support_min = -Inf, 
        support_max = Inf, supp_max_depends_on = c(loc = FALSE, 
        scale = FALSE, shape = FALSE), supp_min_depends_on = c(loc = TRUE, 
        scale = FALSE, shape = FALSE))), list(package = "TLMoments", 
    family = "gum", family_info = list(lower = c(loc = -Inf, 
    scale = 0.01), upper = c(loc = 719.78, scale = Inf), accepts_float = c(loc = TRUE, 
    scale = TRUE), defaults = c(loc = 0, scale = 1), log = FALSE, 
        discrete = FALSE, support_min = -Inf, support_max = Inf, 
        supp_max_depends_on = c(loc = FALSE, scale = FALSE), 
        supp_min_depends_on = c(loc = FALSE, scale = FALSE))), 
    list(package = "TLMoments", family = "ln3", family_info = list(
        lower = c(loc = -Inf, scale = -Inf, shape = 0.01), upper = c(loc = Inf, 
        scale = 710.9, shape = 1001), accepts_float = c(loc = TRUE, 
        scale = TRUE, shape = TRUE), defaults = c(loc = 0, scale = 1, 
        shape = 1), log = FALSE, discrete = FALSE, support_min = -Inf, 
        support_max = Inf, supp_max_depends_on = c(loc = FALSE, 
        scale = FALSE, shape = FALSE), supp_min_depends_on = c(loc = TRUE, 
        scale = FALSE, shape = FALSE))))
