list(list(package = "brms", family = "asym_laplace", family_info = list(
    lower = c(mu = -Inf, sigma = -Inf, quantile = -Inf), upper = c(mu = Inf, 
    sigma = Inf, quantile = Inf), accepts_float = c(mu = TRUE, 
    sigma = TRUE, quantile = TRUE), defaults = c(mu = 0, sigma = 1, 
    quantile = 0.5), log = TRUE, discrete = FALSE, support_min = -Inf, 
    support_max = Inf, supp_max_depends_on = c(mu = FALSE, sigma = FALSE, 
    quantile = TRUE), supp_min_depends_on = c(mu = FALSE, sigma = FALSE, 
    quantile = TRUE))), list(package = "brms", family = "exgaussian", 
    family_info = list(lower = c(mu = -Inf, sigma = 8.32667268468867e-17, 
    beta = 8.32667268468867e-17), upper = c(mu = Inf, sigma = Inf, 
    beta = Inf), accepts_float = c(mu = TRUE, sigma = TRUE, beta = TRUE
    ), defaults = c(mu = 0.5, sigma = 0.5, beta = 0.5), log = TRUE, 
        discrete = FALSE, support_min = -Inf, support_max = Inf, 
        supp_max_depends_on = c(mu = FALSE, sigma = FALSE, beta = FALSE
        ), supp_min_depends_on = c(mu = FALSE, sigma = FALSE, 
        beta = FALSE))), list(package = "brms", family = "frechet", 
    family_info = list(lower = c(loc = -Inf, scale = 0.01, shape = 0.01
    ), upper = c(loc = 9.99, scale = Inf, shape = Inf), accepts_float = c(loc = TRUE, 
    scale = TRUE, shape = TRUE), defaults = c(loc = 0, scale = 1, 
    shape = 1), log = TRUE, discrete = FALSE, support_min = -9.98999999999999, 
        support_max = Inf, supp_max_depends_on = c(loc = FALSE, 
        scale = FALSE, shape = FALSE), supp_min_depends_on = c(loc = FALSE, 
        scale = FALSE, shape = FALSE))), list(package = "brms", 
    family = "gen_extreme_value", family_info = list(lower = c(mu = -Inf, 
    sigma = 0.01, xi = -Inf), upper = c(mu = Inf, sigma = Inf, 
    xi = Inf), accepts_float = c(mu = TRUE, sigma = TRUE, xi = TRUE
    ), defaults = c(mu = 0, sigma = 1, xi = 0), log = TRUE, discrete = FALSE, 
        support_min = -Inf, support_max = Inf, supp_max_depends_on = c(mu = FALSE, 
        sigma = FALSE, xi = FALSE), supp_min_depends_on = c(mu = FALSE, 
        sigma = FALSE, xi = FALSE))), list(package = "brms", 
    family = "inv_gaussian", family_info = list(lower = c(mu = 0.01, 
    shape = 0.01), upper = c(mu = Inf, shape = Inf), accepts_float = c(mu = TRUE, 
    shape = TRUE), defaults = c(mu = 1, shape = 1), log = TRUE, 
        discrete = FALSE, support_min = 0.0100000000000051, support_max = Inf, 
        supp_max_depends_on = c(mu = FALSE, shape = FALSE), supp_min_depends_on = c(mu = FALSE, 
        shape = FALSE))), list(package = "brms", family = "shifted_lnorm", 
    family_info = list(lower = c(meanlog = -Inf, sdlog = 0, shift = -Inf
    ), upper = c(meanlog = 710, sdlog = Inf, shift = Inf), accepts_float = c(meanlog = TRUE, 
    sdlog = TRUE, shift = TRUE), defaults = c(meanlog = 0, sdlog = 1, 
    shift = 0), log = TRUE, discrete = FALSE, support_min = -Inf, 
        support_max = Inf, supp_max_depends_on = c(meanlog = FALSE, 
        sdlog = FALSE, shift = FALSE), supp_min_depends_on = c(meanlog = FALSE, 
        sdlog = FALSE, shift = TRUE))), list(package = "brms", 
    family = "student_t", family_info = list(lower = c(mu = -Inf, 
    sigma = 0.01, df = 0.0100000000000001), upper = c(mu = Inf, 
    sigma = Inf, df = Inf), accepts_float = c(mu = TRUE, sigma = TRUE, 
    df = TRUE), defaults = c(mu = 0, sigma = 1, df = 0.5), log = TRUE, 
        discrete = FALSE, support_min = -Inf, support_max = Inf, 
        supp_max_depends_on = c(mu = FALSE, sigma = FALSE, df = FALSE
        ), supp_min_depends_on = c(mu = FALSE, sigma = FALSE, 
        df = FALSE))), list(package = "brms", family = "von_mises", 
    family_info = list(lower = c(mu = -Inf, kappa = 0), upper = c(mu = Inf, 
    kappa = Inf), accepts_float = c(mu = TRUE, kappa = TRUE), 
        defaults = c(mu = 0.5, kappa = 0.5), log = TRUE, discrete = FALSE, 
        support_min = -Inf, support_max = Inf, supp_max_depends_on = c(mu = FALSE, 
        kappa = FALSE), supp_min_depends_on = c(mu = FALSE, kappa = FALSE
        ))))
