list(list(package = "evd", family = "frechet", family_info = list(
    lower = c(loc = -Inf, scale = 0.01, shape = 0.01), upper = c(loc = Inf, 
    scale = Inf, shape = Inf), accepts_float = c(loc = TRUE, 
    scale = TRUE, shape = TRUE), defaults = c(loc = 0, scale = 1, 
    shape = 1), log = TRUE, discrete = FALSE, support_min = -Inf, 
    support_max = Inf, supp_max_depends_on = c(loc = FALSE, scale = FALSE, 
    shape = FALSE), supp_min_depends_on = c(loc = TRUE, scale = FALSE, 
    shape = FALSE))), list(package = "evd", family = "gev", family_info = list(
    lower = c(loc = -Inf, scale = 0.01, shape = -Inf), upper = c(loc = Inf, 
    scale = Inf, shape = Inf), accepts_float = c(loc = TRUE, 
    scale = TRUE, shape = TRUE), defaults = c(loc = 0, scale = 1, 
    shape = 0), log = TRUE, discrete = FALSE, support_min = -Inf, 
    support_max = Inf, supp_max_depends_on = c(loc = FALSE, scale = FALSE, 
    shape = FALSE), supp_min_depends_on = c(loc = FALSE, scale = FALSE, 
    shape = FALSE))), list(package = "evd", family = "gpd", family_info = list(
    lower = c(loc = -Inf, scale = 0.01, shape = -Inf), upper = c(loc = Inf, 
    scale = Inf, shape = Inf), accepts_float = c(loc = TRUE, 
    scale = TRUE, shape = TRUE), defaults = c(loc = 0, scale = 1, 
    shape = 0), log = TRUE, discrete = FALSE, support_min = -Inf, 
    support_max = Inf, supp_max_depends_on = c(loc = FALSE, scale = FALSE, 
    shape = FALSE), supp_min_depends_on = c(loc = TRUE, scale = FALSE, 
    shape = FALSE))), list(package = "evd", family = "gumbel", 
    family_info = list(lower = c(loc = -Inf, scale = 0.01), upper = c(loc = Inf, 
    scale = Inf), accepts_float = c(loc = TRUE, scale = TRUE), 
        defaults = c(loc = 0, scale = 1), log = TRUE, discrete = FALSE, 
        support_min = -Inf, support_max = Inf, supp_max_depends_on = c(loc = FALSE, 
        scale = FALSE), supp_min_depends_on = c(loc = FALSE, 
        scale = FALSE))), list(package = "evd", family = "nweibull", 
    family_info = list(lower = c(loc = -Inf, scale = 0.01, shape = 0.01
    ), upper = c(loc = Inf, scale = Inf, shape = Inf), accepts_float = c(loc = TRUE, 
    scale = TRUE, shape = TRUE), defaults = c(loc = 0, scale = 1, 
    shape = 1), log = TRUE, discrete = FALSE, support_min = -Inf, 
        support_max = Inf, supp_max_depends_on = c(loc = TRUE, 
        scale = FALSE, shape = FALSE), supp_min_depends_on = c(loc = FALSE, 
        scale = FALSE, shape = FALSE))), list(package = "evd", 
    family = "rweibull", family_info = list(lower = c(loc = -Inf, 
    scale = 0.01, shape = 0.01), upper = c(loc = Inf, scale = Inf, 
    shape = Inf), accepts_float = c(loc = TRUE, scale = TRUE, 
    shape = TRUE), defaults = c(loc = 0, scale = 1, shape = 1
    ), log = TRUE, discrete = FALSE, support_min = -Inf, support_max = Inf, 
        supp_max_depends_on = c(loc = TRUE, scale = FALSE, shape = FALSE
        ), supp_min_depends_on = c(loc = FALSE, scale = FALSE, 
        shape = FALSE))))
