list(list(package = "flexsurv", family = "genf", family_info = list(
    lower = c(mu = -Inf, sigma = 0, Q = -37.5, P = 0), upper = c(mu = 710, 
    sigma = Inf, Q = Inf, P = 1000.5), accepts_float = c(mu = TRUE, 
    sigma = TRUE, Q = TRUE, P = TRUE), defaults = c(mu = 0, sigma = 1, 
    Q = 0.5, P = 0.5), log = TRUE, discrete = FALSE, support_min = 0.0100000000000051, 
    support_max = Inf, supp_max_depends_on = c(mu = FALSE, sigma = FALSE, 
    Q = FALSE, P = FALSE), supp_min_depends_on = c(mu = FALSE, 
    sigma = FALSE, Q = FALSE, P = FALSE))), list(package = "flexsurv", 
    family = "genf.orig", family_info = list(lower = c(mu = -Inf, 
    sigma = 0, s1 = 8.32667268468867e-17, s2 = 0.0100000000000001
    ), upper = c(mu = 713, sigma = 901, s1 = Inf, s2 = Inf), 
        accepts_float = c(mu = TRUE, sigma = TRUE, s1 = TRUE, 
        s2 = TRUE), defaults = c(mu = 0, sigma = 1, s1 = 0.5, 
        s2 = 0.5), log = TRUE, discrete = FALSE, support_min = 0.0100000000000051, 
        support_max = Inf, supp_max_depends_on = c(mu = FALSE, 
        sigma = FALSE, s1 = FALSE, s2 = FALSE), supp_min_depends_on = c(mu = FALSE, 
        sigma = FALSE, s1 = FALSE, s2 = FALSE))), list(package = "flexsurv", 
    family = "gengamma", family_info = list(lower = c(mu = -Inf, 
    sigma = 0, Q = -299.5), upper = c(mu = 710, sigma = Inf, 
    Q = Inf), accepts_float = c(mu = TRUE, sigma = TRUE, Q = TRUE
    ), defaults = c(mu = 0, sigma = 1, Q = 0.5), log = TRUE, 
        discrete = FALSE, support_min = 0.0100000000000051, support_max = Inf, 
        supp_max_depends_on = c(mu = FALSE, sigma = FALSE, Q = FALSE
        ), supp_min_depends_on = c(mu = FALSE, sigma = FALSE, 
        Q = FALSE))), list(package = "flexsurv", family = "gengamma.orig", 
    family_info = list(lower = c(scale = 0, shape = 0, k = 0), 
        upper = c(scale = Inf, shape = Inf, k = Inf), accepts_float = c(scale = TRUE, 
        shape = TRUE, k = TRUE), defaults = c(scale = 1, shape = 0.5, 
        k = 0.5), log = TRUE, discrete = FALSE, support_min = 0, 
        support_max = Inf, supp_max_depends_on = c(scale = FALSE, 
        shape = FALSE, k = FALSE), supp_min_depends_on = c(scale = FALSE, 
        shape = FALSE, k = FALSE))), list(package = "flexsurv", 
    family = "gompertz", family_info = list(lower = c(shape = -1.79, 
    rate = 0.01), upper = c(shape = Inf, rate = Inf), accepts_float = c(shape = TRUE, 
    rate = TRUE), defaults = c(shape = 1, rate = 1), log = TRUE, 
        discrete = FALSE, support_min = 0, support_max = Inf, 
        supp_max_depends_on = c(shape = FALSE, rate = FALSE), 
        supp_min_depends_on = c(shape = FALSE, rate = FALSE))), 
    list(package = "flexsurv", family = "llogis", family_info = list(
        lower = c(shape = 0.01, scale = 0.01), upper = c(shape = Inf, 
        scale = Inf), accepts_float = c(shape = TRUE, scale = TRUE
        ), defaults = c(shape = 1, scale = 1), log = TRUE, discrete = FALSE, 
        support_min = 0.0100000000000051, support_max = Inf, 
        supp_max_depends_on = c(shape = FALSE, scale = FALSE), 
        supp_min_depends_on = c(shape = FALSE, scale = FALSE))), 
    list(package = "flexsurv", family = "weibullPH", family_info = list(
        lower = c(scale = -Inf, shape = 8.32667268468867e-17), 
        upper = c(scale = Inf, shape = Inf), accepts_float = c(scale = TRUE, 
        shape = TRUE), defaults = c(scale = 1, shape = 0.5), 
        log = TRUE, discrete = FALSE, support_min = 0, support_max = Inf, 
        supp_max_depends_on = c(scale = FALSE, shape = FALSE), 
        supp_min_depends_on = c(scale = FALSE, shape = FALSE))))
